# Generated by Django 3.0.7 on 2020-06-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='img',
            field=models.ImageField(upload_to='test'),
        ),
    ]
