# Generated by Django 3.0.7 on 2020-06-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tks', '0002_auto_20200623_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='TestClassTrial',
        ),
    ]
