# Generated by Django 3.0.7 on 2020-06-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tks', '0005_interviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interviews',
            new_name='Interview',
        ),
    ]
