# Generated by Django 3.0.7 on 2020-06-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tks', '0008_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=150)),
                ('Source', models.DateField()),
                ('title', models.CharField(max_length=150)),
            ],
        ),
    ]
