# Generated by Django 3.0.7 on 2020-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tks', '0009_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Source',
            field=models.CharField(max_length=150),
        ),
    ]
