# Generated by Django 3.0.7 on 2020-06-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tks', '0010_auto_20200623_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
