# Generated by Django 3.0.7 on 2020-06-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tks', '0013_auto_20200623_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=150)),
                ('Source', models.CharField(max_length=150)),
                ('Date', models.DateField()),
                ('Link', models.CharField(max_length=150)),
            ],
        ),
    ]
